### ISSUE TITLE
request: privacy.com

### ISSUE THREAD

**Issue by vrillusions** [ambanum/OpenTermsArchive-versions#11]
Not sure where I can suggest new sites to track but all the various pages on privacy.com.  Motivation for this is after logging I'm just told essentially "We updates are terms to better reflect your credit card usage see [here](https://privacy.com/commercial-cardholder-agreement) or click accept" and it just takes you to the page without any overview of what actually changed which was quite annoying.

**Comment by MattiSG** [comment]
Hi Todd! Thank you for suggesting this addition 🙂 

We currently focus on additions of large-scale batches of documents with dedicated partners rather than individual contributions, hence the lack of clear guidance on how to do it.

As an individual contributor, you can try using our [contribution interface](http://contribute.opentermsarchive.org/en/?destination=OpenTermsArchive%2Fcontrib-declarations) to suggest the documents you'd like to track. We make no guarantee on the time it will take to review and add these documents, nor on maintaining them.

As an early assessment for individual contributions, would you say you'd be likely to take responsibility for maintaining these documents after you'd add them? This entails getting notifications when the documents stop being tracked, for example when their URL changes or when the layout of the website changes significantly.

As a last question, I'd be very happy to understand how you discovered Open Terms Archive in your quest for the privacy.com documents 🙂
