### ISSUE TITLE
Request Unity terms of service

### ISSUE THREAD

**Issue by fire** [ambanum/OpenTermsArchive-versions#19]
See https://news.ycombinator.com/item?id=37516523

**Comment by Joshfindit** [comment]
Is it reasonable to capture the changes from before the per-install fee?

This comment outlines how to retrieve the repo that Unity deleted: https://news.ycombinator.com/item?id=37517378

**Comment by MattiSG** [comment]
Thanks for suggesting this addition and to the original poster of the link to Open Terms Archive on Hacker News 🙂

Regarding the addition of Unity: if a service is not already present in our database (which is the case for Unity), you're the best person to add it 🙂 We unfortunately do not have the resources to track every existing ToS and are thus [relying on a network](https://opentermsarchive.org) of partners and volunteers to add terms that are relevant to specific communities. Open Terms Archive is decentralised, and terms are tracked in _collections_ that focus on specific topics, languages, industries…
In this case, you could add Unity to the “Contrib” collection, which is open to any sort of contribution.
To that end you can directly open a pull request by having a look at [existing declarations](https://github.com/OpenTermsArchive/contrib-declarations/tree/main/declarations) and following the [documentation](https://docs.opentermsarchive.org/contributing-terms/) if necessary. You could also try our [beta GUI tool](https://contribute.opentermsarchive.org/?destination=OpenTermsArchive%2Fcontrib-declarations).

> Is it reasonable to capture the changes from before the per-install fee?

Since our goal is to provide a system where you [don't need to trust anyone](https://docs.opentermsarchive.org/design-principles/), Open Terms Archive does not directly enable after-the-fact addition of terms.
Now, what you might very well do is [import that dataset and unify its format](https://docs.opentermsarchive.org/#importing-terms) to the [Open Terms Archive dataset format](https://github.com/OpenTermsArchive/contrib-versions/releases/tag/dataset-contrib-2023-10-02). Let us know if you'd like to volunteer this work and we could help you! 🙂 

I will close this issue as it will not be worked on by Open Terms Archive maintainers, but feel free to discuss further if you'd like!
